package com.deledzis.localshare.util

/** Fragments Tags */
const val HOME_FRAGMENT_TAG = "Home Fragment"
const val NEWS_FRAGMENT_TAG = "News Fragment"
const val EDUCATION_FRAGMENT_TAG = "Education Fragment"
const val EDUCATION_WEBINAR_FRAGMENT_TAG = "Education Webinar Detailed Fragment"
const val EDUCATION_WEBINAR_STUDENTS_FRAGMENT_TAG = "Education Webinar Students Fragment"
const val EDUCATION_WEBINAR_FILES_FRAGMENT_TAG = "Education Webinar Files Fragment"
const val EDUCATION_TEST_START_FRAGMENT_TAG = "Education Test Start Fragment"
const val EDUCATION_TEST_QUESTION_FRAGMENT_TAG = "Education Test Question Fragment"
const val EDUCATION_TEST_RESULTS_FRAGMENT_TAG = "Education Test Results Fragment"
const val EDUCATION_SURVEY_START_FRAGMENT_TAG = "Education Survey Start Fragment"
const val EDUCATION_SURVEY_QUESTION_FRAGMENT_TAG = "Education Survey Question Fragment"
const val EDUCATION_SURVEY_RESULTS_FRAGMENT_TAG = "Education Survey Results Fragment"
const val HANDBOOK_FRAGMENT_TAG = "Handbook Fragment"
const val HANDBOOK_SEARCH_FRAGMENT_TAG = "Handbook Search Fragment"
const val MATERIALS_FRAGMENT_TAG = "Education Materials Fragment"
const val MATERIALS_FOLDER_FRAGMENT_TAG = "Education Materials Folder Fragment"
const val MATERIALS_SEARCH_FRAGMENT_TAG = "Education Materials Search Fragment"
const val LIBRARY_FRAGMENT_TAG = "Library Fragment"
const val DEVELOPMENT_FRAGMENT_TAG = "Employees Progress Fragment"
const val DEVELOPMENT_DETAILED_FRAGMENT_TAG = "Employee Detailed Progress Fragment"
const val RESERVE_FRAGMENT_TAG = "Employees Reserve Fragment"
const val RESERVE_SEARCH_FRAGMENT_TAG = "Employees Reserve Search Fragment"
const val TRUST_POST_FRAGMENT_TAG = "Trust Post Fragment"
const val TRUST_POST_QUESTION_ANSWERS_FRAGMENT_TAG = "Trust Post Question Answers Fragment"
const val SIGN_IN_FRAGMENT_TAG = "Sign In Fragment"
const val RECOVER_FRAGMENT_TAG = "Recover Fragment"
const val PROFILE_FRAGMENT_TAG = "Profile Fragment"
const val NO_INTERNET_FRAGMENT_TAG = "No Internet Fragment"
const val NEWS_NOTE_DETAILED_FRAGMENT_TAG = "News Note Detailed Fragment"

const val APP_PREFERENCES = "prefs"